title: Statamic Bard Mutator
remote_theme: pmarsceill/just-the-docs
search_enabled: true
color_scheme: main
aux_links:
  "Statamic Bard Mutator on GitHub":
    - "https://github.com/jacksleight/statamic-bard-mutator"